[package]
name = "aoc-procmacros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
aoc-utils = { path = "../aoc-utils" }
quote = "1.0.37"
syn = { version = "2.0.90", features = ["extra-traits", "fold", "full", "visit"] }
